server:
  port: 8080

#spring:
#  cloud:
#    gateway:
#      server:
#        webflux:
#          routes:
#            - id: product-service
#              uri: lb://PRODUCT-SERVICE
#              predicates:
#                - Path=/products/**
#              filters:
#                - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
#            - id: order-service
#              uri: lb://ORDER-SERVICE
#              predicates:
#                - Path=/orders/**,/cart/**
#              filters:
#                - "RewritePath=/(?<segment>.*),/api/${segment}"
#            - id: user-service
#              uri: lb://USER-SERVICE
#              predicates:
#                - Path=/users/**
#              filters:
#                - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
#            - id: eureka-server
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/main
#              filters:
#                - SetPath=/
#            - id: eureka-server-static
#              uri: http://localhost:8761
#              predicates:
#                - Path=/eureka/**

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

# Circuit Breaker
resilience4j:
  circuitbreaker:
    instances:
      ecomBreaker:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        sliding-window-type: count_based