spring:
  application:
    name: demo
  profiles:
    active: prod
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  config:
    import: optional:configserver:http://localhost:8222
build:
  id: 000
  version: 0.0.0
  name: "Default-Build"
  type: "Default Build"

server:
  port: 8111
